import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from "../../public/images/profile/pkb-1.png"
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
    
      </Head >
      <main className='flex items-center text-dark min-h-screen'>
      <Layout className='pt-0'>
      <div className='flex items-center justify-between w-full'>
        <div className='w-1/2 pr-0 ' >
          <Image src={profilePic} alt="Prasanna" className='w-full' h-auto />
        </div>
        <div className='w-1/2 flex flex-col items-center self-center'>
          <h1></h1>
          <AnimatedText text="Hi I am Prasanna" className='!text-6xl !text-left'/>

          <p className='my-4 text-base font-medium'>Embarking on a creative journey through frontend development, where each line of code is a brushstroke painting vibrant digital landscapes.</p>
          <div className='flex items-center self-start mt-2'>
            <Link href="/Prasanna_Resume.pdf" target="_blank"
            className='flex items-center bg-dark text-light p-2.5 px-6 
            rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
            border-2 border-solid border-transparent hover:border-dark'
            download={true}
            >Resume<LinkArrow className={"w-5.5 ml-1"}/>
            
            
            </Link>
            <Link href="mailto:prasannabhat345@gmail.com" target="_blank"
            className='ml-4 text-lg font-medium capitalise text-dark underline'>
              Contact</Link>
          </div>
        </div>
      </div>
      
      </Layout>

      <div className='absolute right-8 bottom-8 inline-block w-24'>
        <Image src={lightBulb} alt='Prasanna' className='w-full h-auto'/>
      </div>

      </main>
 
    </>
  )
}
