import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from "../../public/images/profile/pkb-1.png"
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import TransitionEffect from '@/components/TransitionEffect'
import {motion} from 'framer-motion'





export default function Home() {
  return (
    <>
      <Head>
        <title>Prasanna | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
    
      </Head >
      <TransitionEffect/>
      <main className='flex items-center text-dark min-h-screen dark:text-light md:pt-0'>
      <Layout className='pt-0 md:pt-16 sm:pt-0 '>
      <div className='flex items-center justify-between w-full lg:flex-col'
      priority
      sizes="(max-width:768px) 100vw,
      (max-width:1200px) 50vw,
      50vw"
      >
        <div className='w-1/2 pr-0 md:w-full ' >
          <Image src={profilePic} alt="Prasanna" 
           priority
           sizes="(max-width:768px) 100vw,
           (max-width:1200px) 50vw,
           33vw"
          className='w-full h-auto lg:hidden md:inline-block md:w-full '/>
        </div>
        <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
        
          <AnimatedText text="Hi I am Prasanna" className='!text-6xl !text-left 
          xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl'/>

          <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>Embarking on a creative journey through frontend development, where each line of code is a brushstroke painting vibrant digital landscapes.</p>
          <div className='flex items-center self-start mt-2 lg:self-center'>
            <Link href="/Prasanna_Resume.pdf" target="_blank"
            className='flex items-center bg-dark text-light p-2.5 px-6 
            rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
            border-2 border-solid border-transparent hover:border-dark
            dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light
            md:p-2 md:px-4 md:text-base'
            download={true}
            >Resume<LinkArrow className={"w-5.5 ml-1"}/>
            
            
            </Link>
            <Link href="mailto:prasannabhat345@gmail.com" target="_blank"
            className='ml-4 text-lg font-medium capitalise text-dark underline dark:text-light md:text-base'>
              Contact</Link>
          </div>
        </div>
      </div>
      
      </Layout>

      <div className='absolute right-8 bottom-8 inline-block w-24 md:hidden'>
        <Image src={lightBulb} alt='Prasanna' className='w-full h-auto'/>
      </div>

      </main>
 
    </>
  )
}
